apiVersion: v1
kind: Service
metadata:
  name: {{ include "codaui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ include "codaui.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    app: {{ include "codaui.name" . }}
