apiVersion: v1
kind: Service
metadata:
  name: fileingestion
  namespace: {{ .Release.Namespace }}
  labels:
    run: fileingestion
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: fileingestion