apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mailservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "mailservice.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ include "mailservice.name" . }}
    spec:
      containers:
        - name: mailserviceapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: spring.profiles.active
              value: {{ .Values.env.springProfile }}
            - name: env
              value: {{ .Values.env.environment }}
