replicaCount: 2

image:
  repository: codaprodacr.azurecr.io/mailservice
  tag: "prod-BUILD_NUMBER"

env:
  springProfile: prod
  environment: prod

resources: {}
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
