replicaCount: 1

env:
  springProfile: prod
  environment: prod
  javaOpts: "-Xms8g -Xmx24g"

resources:
  requests:
    memory: "24000Mi"
    cpu: "10000m"
  limits:
    memory: "30000Mi"
    cpu: "12000m"

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0