replicaCount: 1

image:
  repository: codaregistry.azurecr.io/netsuiteintegrationservices
  pullPolicy: Always
  tag: "latest"   # overridden per environment

resources:
  requests:
    cpu: 10m
    memory: 512Mi
  limits:
    cpu: 100m
    memory: 1Gi

containerPort: 8081

service:
  type: ClusterIP
  port: 8081

env:
  profile: dev   # overridden per environment
  name: dev

namespace: codadev  # overridden per environment
