apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudgateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: cloudgateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudgateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: cloudgateway
    spec:
      containers:
        - name: cloudgatewayapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: spring.profiles.active
              value: {{ .Values.env.profile | quote }}
            - name: env
              value: {{ .Values.env.name | quote }}
